name: fastapi_test
services:
  fastapi_server:
    build:
      context: /home/cc/Transformer-QA/fastapi_server
      dockerfile: Dockerfile
    container_name: fastapi_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"  # for HTTP requests
    volumes:
      - /mnt/object/meta-llama/Llama-3.1-8B-Instruct:/app/Llama-3.1-8B-Instruct  # TODO: Change this to the final model
    # environment:
    #   - MODEL_PATH=placeholder

  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc:/home/jovyan/work # mount workspace, update to workspace path when everything is ready
      - /mnt/object/meta-llama/Llama-3.1-8B-Instruct:/home/jovyan/Llama-3.1-8B-Instruct
    command: >
      bash -c "python3 -m pip install numpy && start-notebook.sh"

  flask:
    build:
      context: /home/cc/Transformer-QA
      # context: https://github.com/Jasonzzzz28/Transformer-QA.git#serving
    container_name: flask
    ports:
      - "80:5000"
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000
    # volumes:
    #   - /mnt/object/meta-llama/Llama-3.1-8B-Instruct:/app/Llama-3.1-8B-Instruct

  # TODO: Need testing
  prometheus:
  image: prom/prometheus:latest
  container_name: prometheus
  ports:
    - "9090:9090"
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - /mnt/object/prometheus:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /mnt/object/grafana:/var/lib/grafana