name: fastapi_test
services:
  fastapi_server:
    build:
      context: /home/cc/Transformer-QA/fastapi_server
      dockerfile: Dockerfile
    container_name: fastapi_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"  # for HTTP requests
    # environment:
    #   - MODEL_PATH=placeholder

  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc/Transformer-QA:/home/jovyan/work # mount workspace, update to workspace path when everything is ready
    command: >
      bash -c "python3 -m pip install numpy && start-notebook.sh"

  flask:
    build:
      context: /home/cc/Transformer-QA
      # context: https://github.com/Jasonzzzz28/Transformer-QA.git#serving
    container_name: flask
    ports:
      - "80:5000"
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000
    volumes:
      - ./Transformer-QA/opt-125m.pth:/app/opt-125m.pth  # local to container path

# TODO: Need testing